### ISSUE TITLE
Error "Please add a @NgModule annotation" with Angular 5

### ISSUE THREAD

**Issue by Mawster** [rafaesc/ng2-konva#1]
It seems that there is some kind of bug with ng2-konva using with Angular 5.0.3

Reproduce:
1) Create a new project with angular CLI  (1.5.4)
2) Install the actual ng2-konva version 
3) Follow the quick starte guide from here https://www.npmjs.com/package/ng2-konva
4) Try to build production: ng build --prod

This will give you the following error:
ERROR in Error: Unexpected value 'KonvaModule in C:/private/projects/testkonva/node_modules/ng2-konva/dist/index.d.ts' imported by the module 'AppModule in C:/private/projects/testkonva/src/app/app.module.ts'. Please add a @NgModule annotation.

Thanks in advance!

**Comment by rafaesc** [comment]
Hi @Mawster,

I haven't had problems with Angular 5.0.3, and followed all your steps.
Try to run this repository
https://github.com/rafaesc/ng2-konva-demo

feel free to reopen this issue if it still can't work

**Comment by Mawster** [comment]
Thanks for your quick response, but still the same error with your demo repo.
1) Cloned your repo
2) build with ng build -prod

![image](https://user-images.githubusercontent.com/9032520/33227161-627d54fa-d19d-11e7-9701-6a36a5b229a7.png)

Will try it at home on my desktop maybe it works there.

**Comment by Mawster** [comment]
Thanks for your quick response, but still the same error with your demo repo.
1) Cloned your repo
2) build with ng build -prod
![image](https://user-images.githubusercontent.com/9032520/33227193-f1d0457c-d19d-11e7-9f2d-1dce07f0a755.png)

I will try it on my desktop - maybe it works there.

**Comment by Mawster** [comment]
@rafaesc the same problem on my desktop computer.

**Comment by rafaesc** [comment]
Yes, I was able to replicate the problem on my computer, however, I couldn't solve it. maybe I need more time to resolve it.

**Comment by rafaesc** [comment]
Hi @Mawster,

I've published the fix under v2.0.2.
feel free to reopen this issue if it still can't work

Regards
