### ISSUE TITLE
Using concurrently `konva` and `ng2-konva` leads to a falsely error warning

### ISSUE THREAD

**Issue by mlc-mlapis** [rafaesc/ng2-konva#11]
Hi,

I found out that in cases when a new instance of any class from `konva` library is created before instantiating `ng2-konva` components leads to the following falsely error warning (lines 629 - 634 in `ng2-konva.js`):

```
if (glob.Konva) {
   console.error(
      'Konva instance is already exist in current eviroment. ' +
      'Please use only one instance.'
   );
}
```
In our case it is a situation when SystemJS loader already loaded `konva.min.js` lib (because of any its class is used, like `this.tween = new Tween({...})`) and only after that `ng2-konva.umd.min.js` is loaded when any `ng2-konva` component is instantiated.

The case doesn't mean that any lib is loaded twice at all.

**Comment by rafaesc** [comment]
Hi @mlc-mlapis,
I could fix the issue,
Out in 2.0.6!

Regards

**Comment by mlc-mlapis** [comment]
@rafaesc ... olé, it works. Thank you!
