### ISSUE TITLE
ng2-konva not working in angular 4

### ISSUE THREAD

**Issue by kirtiesl** [rafaesc/ng2-konva#2]
Hi,

Getting following errors:

ERROR in node_modules/konva/konva.d.ts (550,84): Cannot find name 'ImageBitmap'.

ERROR in node_modules/konva/konva.d.ts (551,84): Cannot find name 'ImageBitmap'.

ERROR in node_modules/konva/konva.d.ts (552,84): Cannot find name 'ImageBitmap'.

ERROR in node_modules/konva/konva.d.ts (572,23): Cannot find name 'Path2D'.

angular version: 4
angular/cli: 1.0.6
node: 6.9.2

**Comment by rafaesc** [comment]
Hi @kirtiesl,

That error is in the konva module, can you share your code where use konva?

**Comment by kirtiesl** [comment]
I have Installed through npm like-
 npm install konva ng2-konva --save

and imported in app.module.ts  - 
import { KonvaModule } from 'ng2-konva';

getting above error.

**Comment by rafaesc** [comment]
Please try to install the version ng2-konva@1.0.8

**Comment by rafaesc** [comment]
Thanks for responding, I will have to create a sample project to replicate the issue. I hope that the weekend I fix that

Regards.

**Comment by rafaesc** [comment]
Hi @kirtiesl,

I've published the fix under v2.0.2.
feel free to reopen this issue if it still can't work

Regards

**Comment by fvadouko** [comment]
Hi,

it still can't work under v2.0.2. I installed it and set up it, like in this link : https://www.npmjs.com/package/ng2-konva.
