### ISSUE TITLE
NG2-KONVA components not recognized in Angular 5.1.0 template

### ISSUE THREAD

**Issue by mlc-mlapis** [rafaesc/ng2-konva#4]
@rafaesc Hi,

after installing `konva` and `ng2-konva` and specifying all necessary metadata in a module and trying to place some basic components in a template, VSC editor (version 1.18.1) is unable to find out those components and there is an error like `'ko-stage' is not a known element`, `'ko-layer' is not a known element` or `'ko-circle' is not a known element`.

Also when trying to compile using `ngc`, it has a problem with the imported `KonvaModule` which leads to `error TS2307: Cannot find module './app.module.ngfactory' ... Unexpected value 'KonvaModule in C:/.../node_modules/ng2-konva/dist/index.d.ts' imported by the module 'AppModule in C:/.../aot/app/app.module.ts'. Please add a @NgModule annotation.`

I think that this behavior can be related to requirements for Package Format 5.0 which `ng2-konva` doesn't fulfill ... `import { KonvaModule } from 'ng2-konva';` leads to `module ".../node_modules/ng2-konva/dist/index"` ... and I am not sure if it is correct due to Package Format 5.0.

The only way how to compile this simple case and also run it without a problem is just only in JIT mode.

```
import { KonvaModule } from 'ng2-konva';
...
@NgModule({
	...
	imports: [
		...
		KonvaModule
	],
	...
})
```
```
<ko-stage [config]="configStage">
	<ko-layer>
		<ko-circle [config]="configCircle" (click)="handleClick($event)"></ko-circle>
	</ko-layer>
</ko-stage>
```

**Comment by mlc-mlapis** [comment]
*Distributing an Angular Library - Checklist*
http://blog.mgechev.com/2017/01/21/distributing-an-angular-library-aot-ngc-types

... just picking some of them:

* Reference the esm version under the `module` and `jsnext:main` properties in package.json.
* Provide ES5 UMD bundle of your library and reference it under the `main` property.
* Provide the type definitions of your library by generating them with tsc with the declaration flag set to true. Reference the type definitions corresponding to the main module of your package in the `types` property in your package.json.
* Compile your library with ngc and include the generated *.metadata.json files in your package.
* The tsconfig.json used by ngc should have skipTemplateCodegen set to true, under angularCompilerOptions.

**Comment by mlc-mlapis** [comment]
@rafaesc ... recently I checked `ng-packagr` as a tool for develop and build libs and I have to say that using it means the easiest way how to produce a good production lib which is also very easy to use for any developer. Try to think if switching to it would help you ... us to use more easily our lib.

**Comment by rafaesc** [comment]
Hi @mlc-mlapis,

Thanks for your recommendations, I have tried to fix this issue copying this lib
https://github.com/mgechev/ngresizable
On the [article](http://blog.mgechev.com/2017/01/21/distributing-an-angular-library-aot-ngc-types/) that you share, he takes that as example, I assumed it would work but not

My advance is in beta branch, I will try with `ng-packagr`, thanks

Regards

**Comment by mlc-mlapis** [comment]
@rafaesc ... ok, if you have any problems with `ng-packagr` try to ask ... I used the tool 2 days ago for the first time and I have to say that it is a really easy way ... the only problem I had was not related to `ng-packagr` directly but probably with `Angular Language Service extension in VSC` ... https://github.com/angular/angular/issues/21066

**Comment by rafaesc** [comment]
Hi @mlc-mlapis,

It work, thanks for the support.
I've published the fix under v2.0.2.
Please try it and let me know if it works.

Regards!

**Comment by mlc-mlapis** [comment]
@rafaesc ... bingo ... my previous test works now without problems. Good work! Now I am able to try a more sophisticated things ...

**Comment by rafaesc** [comment]
Perfect!

Thanks again @mlc-mlapis
