### ISSUE TITLE
Version 2.0.3 is unusable ... wrong package format

### ISSUE THREAD

**Issue by mlc-mlapis** [rafaesc/ng2-konva#6]
Rafael, version 2.0.3 is unusable ... just wrong package format. Version 2.0.2 was OK.

**Comment by rafaesc** [comment]
Hi @mlc-mlapis,

Please, can you try with v2.0.4?

Regards

**Comment by mlc-mlapis** [comment]
@rafaesc ... Yep, v2.0.5 is fine. 👍  Thanks.
